dist: bionic

services:
  - docker

env:
  global:
    - BATECT_CACHE_TYPE=directory
    - BATECT_ENABLE_TELEMETRY=true
    # GPG_KEY_PASSPHRASE:
    - secure: "iT+68YhJqPhlG0KR3GrNUlKf2pCaH4Hm4+4lY2byhlfeN3gakRPUBdfDjn6xzyziBXSLwj6EjUzZmMxCUQQGaENAhF3hrFtMRRFVOoLf3O4Uv8qMiIzk3Y7ULPRJPZzaqafW1a9K3LFNSHm47Wf2Wsf9rfO0dmatFkbsTMlJvb/FkbQWbqdDM7kxNNcpMQUmiFZ+j+sjWlabH+rc9Hi/uOjg95hHW4YWu4f43ROKzfaWX+75URAQ8Ih2Tw/oHNkvwMlOlVd9Csb5T3fvmTGBvdAPntLIdN/Iz7rionzMP3EUm2tC49A1PNRxLAEF4zNim9cHCbHGNpJnnWsPux9N128s+i1KMFtxZR5tBqSbX/gO2CN+SQJiSUvMx2Zu7NgRwsz1tYD8667i65//ZtrQbAvaSjxOSav0Q6Cdz/PlCWbfOmActwRxdEdrt+CtYnh2XyBmzLySDFqEjRCa5zedJrMJ2WbAxxmL/UgyMRYLbOEk5/7NR2q7ZX3FCWj+FJdQbRxayJ/6cltB4DYAXqdHv1hpWVgQGTfUkhiHunAuZygOl44pLeEWi4j6ETB8xzgscgcO0wzjToHcpnWQvDBnpkm26uCaR8jcn2ObEbBci1QdaRch9PfV81YIAL9Ssay/WQktGE/Ewe0Gm2DOcU0YWvU3BJixL50Wc1UBYGt+Xxw="
    - GPG_KEY_ID=6382A4D7
    - OSSRH_USERNAME=charleskorn-travis
    # OSSRH_PASSWORD:
    - secure: "sWRpLLq0B2GveAEeHjXViVoCumxPEHooGmpcFunN/lHOYC44Kz5hzh1oXzeZFuBEuE0DwhqZIi6ZIY3rq4wBe4HsCwVqR9kBeyYQ3LZ2cocLOAhvXWXufenxz+0Q8gSAOR6zJaN9xv6muojixd3CWbMK/P082/PFI8sFvGXLqw874BRrojvPTTfNdemQYs7X+wpm7bJFHVnwgvdm/o6Cg2YAadF9JMJ6r25sjEHmxE50+Nhc9pKfQQujNPrM4vbOB3N/C0IU//FaH0mrXbkf2UohkW/Ku1mW59jpfUhlLOS/zLxdO4KvzrjSzfm5ASSHCj1gN2hzEOouvTRdBbTDj8GvN3Jb6p1XgoYtXk8Okbr+urpqHM9PEIgbeTR8j+5rkCsKU3uSUF+VH+yeUso6U8jDjB4FGHbW6eww0iFUlrStFUmfxzOnMkzfjBRQzc25Xwmf4lkLUW9SL0My8Ff53FOpy6QL1qdX+f4vHKxPDY5x9HoNPePg1Wn1JZygBx29fBC7LJk8kJiDzRhYlLkwwkDHma0vRmvO1fhwSXE3sHX8kfvBLThZks784PL4uDTxtMi0TI753vV187APfo46C3WgO5MVu6CnuIOWsnBApIoCo6ZgeFB9kvIP3/TW8/+D7pNruYeF/bEN1AFTS4uIVk+4gcChJQtr81YJP3jhZ7w="

before_install:
  - docker --version

  # We can't use an environment variable for this because Travis doesn't support encrypted environment variables large enough to hold it.
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then export GPG_KEY_RING="$(openssl aes-256-cbc -K $encrypted_2ebe366193ee_key -iv $encrypted_2ebe366193ee_iv -in travis/keyring.enc -out /dev/stdout -d)"; fi

script: ./travis/build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: ./batect publishSnapshot
    skip_cleanup: true
    on:
      tags: false
      repo: charleskorn/kaml
      condition: $TRAVIS_BRANCH = "master" # We can't use branch: master here because we're using tags: false (see https://docs.travis-ci.com/user/deployment/#conditional-releases-with-on)

  - provider: script
    script: ./batect publishRelease
    skip_cleanup: true
    on:
      tags: true
      repo: charleskorn/kaml

  - provider: releases
    api_key:
      secure: H+DP0+Xs/B1CJH80NHqWdCuB9gyFfOCNFQ+I2lP7v/oj8SHABg+D41MNu0iUfPPEHjbFa3XmIPG1ij2koHeS6E3L1Vf310Cq4oUsahViMhf7EG9e1bDwiiXq2+/VhJVHNuLmj9INpcA/thepgEeFJqO9A36Zl4kiRYmqu8ghKoKTmLhhBrycVzhZmziUaoXM3VLv2FY+uDQsrB1fQwX7e7QVBJMOcqe0XLyFdaAoVd7mWHMg1AduhWyxy0Jzj+EHxb5IQJPf5qLxogDQ8cyW0JTpRobeCV2qxTpQYwGvAluNm426WDNcFNUu5U9FGMMZJ1UEJLEahi2WnBWe1zJOPln2cmjefNPVT5bdCahEEnFBjlG8+duFr97RCcN9VYy2C5Febv4cuhtJz4DXPwzT3YVdPQC02pBZhclDE/oLNwHAGRjWnPmGWEXrjXDhl7tANLgv3hkkHZZDAvyLReSaDZ9UFb8dL4UygW/XT+8fYaeN30t6Tpaap37T328Hp2df5bqY6bPFqgdRTohMQ8ce5BSm6y8fnvhibkEmkKY9jt+DAyIHEeADq/i0rJmmETAlsCuzRSu2g+bv5gI4sYFzELbgCkgr9EhmlX3V+Canh5C3ncoYA/M5zfRNAKPdTaVkRfwtoEy11fEPNHX7GTN8aVOlMstEN+QfQcCm66+gHMU=
    skip_cleanup: true
    file_glob: true
    file: build/release/*
    on:
      tags: true
      repo: charleskorn/kaml

before_cache:
  - rm -f  .batect/caches/gradle-cache/caches/modules-2/modules-2.lock
  - rm -fr .batect/caches/gradle-cache/caches/*/plugin-resolution/
  - rm -fr .batect/caches/gradle-cache/caches/*/scripts/
  - rm -fr .batect/caches/gradle-cache/caches/*/scripts-remapped/
  - rm -fr .batect/caches/gradle-cache/caches/*/fileHashes/
  - rm -f  .batect/caches/gradle-cache/caches/*/fileContent/*.lock
  - rm -f  .batect/caches/gradle-cache/caches/*/javaCompile/*.lock
  - rm -f  .batect/caches/gradle-cache/caches/*/executionHistory/*.lock
  - rm -f  .batect/caches/gradle-cache/caches/*/generated-gradle-jars/*.lock
  - rm -f  .batect/caches/gradle-cache/caches/jars-3/*.lock
  - rm -f  .batect/caches/gradle-cache/caches/jars-8/*.lock
  - rm -f  .batect/caches/gradle-cache/caches/transforms-1/transforms-1.lock
  - rm -f  .batect/caches/gradle-cache/caches/journal-1/file-access.bin
  - rm -f  .batect/caches/gradle-cache/caches/journal-1/*.lock
  - rm -f  .batect/caches/gradle-cache/kotlin-profile/*

cache:
  directories:
    - .batect/caches
